services:
  marquez-db:
    image: postgres:14
    container_name: marquez_db
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    ports:
      - "5433:5432"
    networks:
      - factorhouse
    profiles:
      - lineage
    environment:
      - POSTGRES_USER=marquez
      - POSTGRES_PASSWORD=marquez
      - POSTGRES_DB=marquez
    volumes:
      - ./resources/marquez/db-config:/etc/postgresql

  marquez-api:
    image: marquezproject/marquez:0.51.1
    container_name: marquez-api
    entrypoint:
      [
        "/opt/marquez/wait-for-it.sh",
        "marquez-db:5432",
        "--",
        "./entrypoint.sh",
      ]
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - factorhouse
    profiles:
      - lineage
    env_file:
      - resources/marquez/setup.env
    volumes:
      - ./resources/marquez/config/wait-for-it.sh:/opt/marquez/wait-for-it.sh
      - ./resources/marquez/config/marquez.dev.yml:/usr/src/app/marquez.dev.yml

  marquez-web:
    image: marquezproject/marquez-web:0.51.1
    container_name: marquez-web
    ports:
      - "3003:3000"
    networks:
      - factorhouse
    profiles:
      - lineage
    env_file:
      - resources/marquez/setup.env
    depends_on:
      - marquez-api

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "19090:9090"
    networks:
      - factorhouse
    profiles:
      - telemetry
    volumes:
      - ./resources/kpow/prometheus/kpow-scrap-config${KPOW_SUFFIX:-}.yml:/etc/prometheus/scrape_configs/kpow-scrap-config.yml
      - ./resources/kpow/prometheus/kpow-rules${KPOW_SUFFIX:-}.yml:/etc/prometheus/rules/kpow-rules.yml
      - ./resources/flex/prometheus/flex-scrap-config${FLEX_SUFFIX:-}.yml:/etc/prometheus/scrape_configs/flex-scrap-config.yml
      - ./resources/flex/prometheus/flex-rules${FLEX_SUFFIX:-}.yml:/etc/prometheus/rules/flex-rules.yml
      - ./resources/flink/prometheus/flink-scrap-config.yml:/etc/prometheus/scrape_configs/flink-scrap-config.yml
      - ./resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    ports:
      - "19093:9093"
    networks:
      - factorhouse
    profiles:
      - telemetry
    volumes:
      - ./resources/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  grafana:
    image: grafana/grafana:12.1.1
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3004:3000"
    networks:
      - factorhouse
    profiles:
      - telemetry
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./resources/grafana:/etc/grafana/provisioning

networks:
  factorhouse:
    external: ${USE_EXT:-true}
    name: factorhouse
