scrape_configs:
  - job_name: "flink"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "jobmanager:9249"
          - "taskmanager-1:9249"
          - "taskmanager-2:9249"
          - "taskmanager-3:9249"
