scrape_config_files:
  - /etc/prometheus/scrape_configs/kpow-scrap-config.yml
  - /etc/prometheus/scrape_configs/flex-scrap-config.yml
  - /etc/prometheus/scrape_configs/flink-scrap-config.yml

rule_files:
  - /etc/prometheus/rules/kpow-rules.yml
  - /etc/prometheus/rules/flex-rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
