scrape_configs:
  - job_name: "kpow"
    metrics_path: "/metrics/v1"
    static_configs:
      - targets: ["kpow:3000"]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(.*)"
        target_label: __name__
        replacement: "kpow_$1"
  - job_name: "flex"
    metrics_path: "/metrics/v1"
    static_configs:
      - targets: ["flex:3000"]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(.*)"
        target_label: __name__
        replacement: "flex_$1"
  - job_name: "flink"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "jobmanager:9249"
          - "taskmanager-1:9249"
          - "taskmanager-2:9249"
          - "taskmanager-3:9249"

rule_files:
  - kpow-rules.yml
  - flex-rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
