scrape_configs:
  - job_name: "flex"
    metrics_path: "/metrics/v1"
    static_configs:
      - targets: ["flex:3000"]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(.*)"
        target_label: __name__
        replacement: "flex_$1"
