## Note: All Kpow metrics are prefixed by 'kpow_'!
groups:
  - name: KpowAlerts
    rules:
      - alert: UnhealthyConsumer
        expr: kpow_group_state == 0 or kpow_group_state == 1 or kpow_group_state == 2
        for: 5m
        annotations:
          summary: "Consumer {{ $labels.target }} is unhealthy"
          description: "The Consumer Group {{ $labels.target }} has gone into {{ $labels.state }} for cluster {{ $labels.id }}"
      - alert: UnhealthyConnectorTask
        expr: kpow_connect_connector_task_state != 1
        for: 5m
        annotations:
          summary: "Connect task {{ $labels.target }} is unhealthy"
          description: "The Connector task {{ $labels.target }} has gone into {{ $labels.target }} for cluster {{ $labels.id }}"
      - alert: UnhealthyConnector
        expr: kpow_connect_connector_state != 1
        for: 5m
        annotations:
          summary: "Connector {{ $labels.target }} is unhealthy"
          description: "The Connector {{ $labels.target }} has gone into {{ $labels.target }} for cluster {{ $labels.id }}"
      - alert: LaggingConsumerGroup
        expr: kpow_group_offset_lag > 5000
        for: 5m
        annotations:
          summary: "Consumer group {{ $labels.target }} is lagging"
          description: "Consumer group {{ $labels.target }} is lagging for cluster {{ $labels.id }}"
      - alert: KpowDown
        expr: up == 0 and {job="kpow"}
        for: 1m
        annotations:
          summary: "Kpow is down"
          description: "Kpow instance {{ $labels.instance }} has been down for more than 1 minute."
