{
 "title": "Kafka Connect",
 "tags": [
  "kafka",
  "kpow",
  "connect"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(kpow_connect_connector_total, env)"
   }
  ]
 },
 "panels": [
  { "title": "Connector Summary Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Connectors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kpow_connect_connector_total{env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(kpow_connect_connector_running_total{env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(kpow_connect_connector_paused_total{env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kpow_connect_connector_failed_total{env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Unassigned",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(kpow_connect_connector_unassigned_total{env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Unreachable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum(kpow_connect_connector_unreachable_total{env=~\"$env\"})"
    }
   ]
  },
  { "title": "Task Summary Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(kpow_connect_task_total{env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "sum(kpow_connect_task_running_total{env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "sum(kpow_connect_task_paused_total{env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "sum(kpow_connect_task_failed_total{env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Unassigned",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "targets": [
    {
     "expr": "sum(kpow_connect_task_unassigned_total{env=~\"$env\"})"
    }
   ]
  },
  { "title": "Detailed Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Connector Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "kpow_connect_connector_state{env=~\"$env\"}"
    }
   ]
  },
  {
   "title": "Task Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "kpow_connect_connector_task_state{env=~\"$env\"}"
    }
   ]
  }
 ]
}