{
 "title": "Kafka Topic",
 "tags": [
  "kafka",
  "kpow",
  "topic"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(kpow_topic_count, env)"
   },
   {
    "name": "topic_name",
    "label": "Topic",
    "query": "label_values(kpow_topic_bytes_disk{env=~\"$env\"}, target)"
   }
  ]
 },
 "panels": [
  { "title": "Environment Summary Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kpow_topic_count{env=~\"$env\", target=\"all\"})"
    }
   ]
  },
  {
   "title": "Total Replica Disk",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kpow_topic_bytes_disk_total{env=~\"$env\", target=\"all\"})"
    }
   ]
  },
  {
   "title": "Write/s (msgs)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kpow_topic_end_delta_total{env=~\"$env\", target=\"all\"})"
    }
   ]
  },
  {
   "title": "Read/s (msgs)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kpow_group_offset_delta_total{env=~\"$env\", target=\"all\"})"
    }
   ]
  },
  {
   "title": "Non-Preferred Leaders",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(kpow_topic_non_preferred_leaders_total{env=~\"$env\", target=\"all\"})"
    }
   ]
  },
  {
   "title": "Total URPs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum(kpow_topic_urp_total{env=~\"$env\", target=\"all\"})"
    }
   ]
  },
  {
   "title": "Topic Production & Consumption Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Topic Production Throughput (m/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kpow_topic_end_delta{env=~\"$env\", target=~\"$topic_name\", quantile=\"0.95\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Topic Consumption Throughput (m/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "kpow_topic_offset_delta{env=~\"$env\", target=~\"$topic_name\", quantile=\"0.95\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  { "title": "Topic Size & Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Topic Size Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kpow_topic_bytes_disk{env=~\"$env\", target=~\"$topic_name\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Topic Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kpow_topic_offset_lag{env=~\"$env\", target=~\"$topic_name\", quantile=\"0.95\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  { "title": "URP Diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "URPs by Topic",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "kpow_topic_urp{env=~\"$env\", target=~\"$topic_name\"}"
    }
   ]
  }
 ]
}