{
 "title": "Kafka Environment",
 "tags": [
  "kafka",
  "kpow",
  "environment"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(kpow_broker_count, env)"
   }
  ]
 },
 "panels": [
  { "title": "Key Environment Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Online Brokers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kpow_broker_count{env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Total Data on Disk",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kpow_topic_bytes_disk_total{env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Total Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(kpow_topic_count{env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Total Consumer Groups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kpow_group_count{env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Stable Consumer Groups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "count(kpow_group_state{env=~\"$env\", state=\"Stable\"})"
    }
   ]
  },
  {
   "title": "URP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum(kpow_topic_urp_total{env=~\"$env\"})"
    }
   ]
  },
  { "title": "Performance Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(kpow_topic_end_delta_total{env=~\"$env\"})",
     "legendFormat": "Write Rate (msgs/sec)"
    },
    {
     "expr": "sum(kpow_topic_bytes_disk_total{env=~\"$env\"})",
     "legendFormat": "Total Data on Disk"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(kpow_group_offset_delta_total{env=~\"$env\"})",
     "legendFormat": "Read Rate (msgs/sec)"
    },
    {
     "expr": "sum(kpow_group_offset_lag_total{env=~\"$env\"})",
     "legendFormat": "Total Lag"
    }
   ]
  },
  { "title": "Cluster Health & Stability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Topic Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count(kpow_topic_production_inactive_mins{env=~\"$env\"} < 5 and kpow_topic_consumption_inactive_mins{env=~\"$env\"} < 5)",
     "legendFormat": "Active (Read/Write)"
    },
    {
     "expr": "count((kpow_topic_consumption_inactive_mins{env=~\"$env\"} < 5) unless (kpow_topic_production_inactive_mins{env=~\"$env\"} < 5))",
     "legendFormat": "Read-Only"
    },
    {
     "expr": "count((kpow_topic_production_inactive_mins{env=~\"$env\"} < 5) unless (kpow_topic_consumption_inactive_mins{env=~\"$env\"}))",
     "legendFormat": "Write-Only"
    },
    {
     "expr": "count((kpow_topic_production_inactive_mins{env=~\"$env\"} >= 5) unless (kpow_topic_consumption_inactive_mins{env=~\"$env\"} < 5))",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Consumer Group Health",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "count(kpow_group_state{env=~\"$env\", state=\"Stable\"})",
     "legendFormat": "Stable"
    },
    {
     "expr": "count(kpow_group_state{env=~\"$env\", state=\"Rebalancing\"})",
     "legendFormat": "Rebalancing"
    },
    {
     "expr": "count(kpow_group_state{env=~\"$env\", state=\"Empty\"})",
     "legendFormat": "Empty"
    }
   ]
  }
 ]
}