name: Release Factorhouse Flink Docker Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: |
          The image tag for the Factorhouse Flink Docker image. 
          This tag should match the LTS release version of Flink, 
          as listed in the Flink documentation: 
          [https://nightlies.apache.org/flink/flink-docs-lts/](https://nightlies.apache.org/flink/flink-docs-lts/). 
          Expected format: X.Y.Z (e.g., 1.20.1).
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log into DockerHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Factorhouse Flink Docker Image
        run: |
          IMAGE_TAG=${{github.event.inputs.image_tag}}
          .github/workflows/scripts/validate-image-tag.sh "$IMAGE_TAG"

          FLINK_DOCKER_FILE_PATH=./resources/flex/docker
          docker buildx build -f $FLINK_DOCKER_FILE_PATH/Dockerfile \
            --platform=linux/amd64,linux/arm64 -t factorhouse/flink:latest --push $FLINK_DOCKER_FILE_PATH
          docker buildx build -f $FLINK_DOCKER_FILE_PATH/Dockerfile \
            --platform=linux/amd64,linux/arm64 -t factorhouse/flink:lts --push $FLINK_DOCKER_FILE_PATH
          docker buildx build -f $FLINK_DOCKER_FILE_PATH/Dockerfile \
            --platform=linux/amd64,linux/arm64 -t factorhouse/flink:$IMAGE_TAG --push $FLINK_DOCKER_FILE_PATH
