name: release

on:
  push:
    tags: ["v*"] # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        uses: ghalactic/github-release-from-tag@v5
        with:
          prerelease: "false"
          draft: "true"
